language: java
jdk: openjdk8
before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
script:
    - fossa init
    - fossa analyze
notifications:
    webhooks:
        - https://oapi.dingtalk.com/robot/send?access_token=be28d8d6223fc97c0c8540546a5b7bd0f54ac71f70e308ba40afe5d3db739e8d
